// In-game HUD (M3). Mount <Hud /> over the board; it reads everything through ../contract.
export { Hud } from './Hud'
export { TopBar } from './TopBar'
export { ActivationPanel } from './ActivationPanel'
export { PromptDock } from './Prompt'
export { GridCard, GridCardFor } from './GridCard'
export { EventFeed } from './EventFeed'
export { GameOver } from './GameOver'
export { buildPromptView } from './promptView'
export { groupActions } from './activationView'
export { buildFeed } from './feedView'
export { cardDamage } from './gridView'
export { DiceTray } from '../dice/DiceTray'
export { DiceLog } from '../dice/DiceLog'
