// Public surface of the client audio module.
export { audio, initAudio } from './audio'
export { AudioManager, MUSIC_DB, DUCK_DB } from './manager'
export type { AudioStats, PlayOptions } from './manager'
export { MusicDirector, BATTLE_ORDER, CROSSFADE_S } from './music'
export type { MusicScene } from './music'
export { DEFAULT_AUDIO_SETTINGS, loadAudioSettings, saveAudioSettings, sanitizeAudioSettings } from './settings'
export type { AudioSettings } from './settings'
export { soundsForEvent, playEventSounds, attackSound, spellSound, endVoice, endScene } from './eventSounds'
export type { EventSound, SoundContext } from './eventSounds'
export { playBeatAudio, humanSeat } from './beatAudio'
export { useAudioSettings } from './useAudioSettings'
export { SoundSettings } from './SoundSettings'
export { AUDIO_ASSETS, AUDIO_BY_ID, audioPath } from './manifest'
